# The URL the site will be built for
base_url = "https://trolocsis.com"
title = "Ryan's Blog"
theme = "apollo"
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
generate_feeds = true
compile_sass = true
build_search_index = true
taxonomies = [{ name = "tags", feed = true, paginate_by = 10 }]

[slugify]
paths = "on"
taxonomies = "on"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
author = "Ryan Phillips"
toc = true
use_cdn = false
theme = "auto"
fancy_code = true
mathjax = true
mathjax_dollar_inline_enable = true
comment = ""

blog_menu = [
  { url = "$BASE_URL/categories", name = "Categories" },
  { url = "$BASE_URL/tags", name = "Tags" },
  { url = "$BASE_URL/about", name = "About" },
  { url = "https://github.com/rphillips", name = "Github" },
]

socials = [
  { name = "github", url = "https://github.com/rphillips", icon = "github" },
]

menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  # { name= "/projects", url= "/projects", weight= 2 },
  { name = "/about", url = "/about", weight = 2 },
  { name = "/tags", url = "/tags", weight = 3 },
]
